export type BusinessUnit = 'E-HAILING' | 'DAILY RENTAL' | 'SMART DRIVE' | 'SAMBUNG BAYAR';
export type MonthStatus = 'DRAFT' | 'READY FOR REVIEW' | 'CLOSED';
export interface FinanceVehicle { plate_key: string; display_plate: string; business_unit: BusinessUnit; ownership_type: string; status: string; deleted_at?: string | null }
export interface RecurringCost { id?: string; plate_key: string; start_month: string; end_month: string | null; cost_type: string; monthly_amount: number; payee: string | null; notes: string | null }
export type InsuranceResponsibility = 'ECA_PAID' | 'OWNER_PAID';
export interface Insurance { id?: string; plate_key: string; premium: number; payment_date: string | null; coverage_start: string | null; coverage_end: string | null; responsibility?: InsuranceResponsibility | null; supplier?: string | null; reference?: string | null; source?: string | null }
export interface FinanceExpense { id?: string; finance_month: string; billing_date: string | null; plate_key: string | null; category: string; payment_source: 'Workshop Billing' | 'Vehicle Direct Cost' | 'Corporate Opex'; supplier: string | null; amount: number; reference: string | null; description: string | null; frequency?: 'MONTHLY_RECURRING' | 'ONE_OFF'; start_month?: string | null; end_month?: string | null; source?: string | null; notes?: string | null }
export interface EhailingPayment { source_payment_id: string; driver_id: string | null; driver_name_snapshot: string | null; car_plate_snapshot: string | null; plate_key: string | null; payment_date: string; cash_amount: number; service_claim: number; gross_rental_revenue: number; payment_method: string | null; refreshed_at: string; finance_month: string; attribution_changed: boolean }
export interface SmartDriveRow { source_row: number; sheet_name: string; reference: string | null; plate_key: string; display_plate: string; pickup_date: string; return_date: string; gross_revenue: number; commission: number; status: string; payment_status: string | null }
export interface FinanceImport { id: string; finance_month: string; kind: 'SMART_DRIVE' | 'BOOTSTRAP' | 'WORKSHOP'; filename: string; imported_at: string; row_count: number; status: 'POSTED' | 'REPLACED'; source_hash: string | null }
export interface FinanceMonth { finance_month: string; status: MonthStatus; revision: number; refreshed_at: string | null; frozen_at: string | null; source_count: number; total_cash: number; total_claim: number; earliest_date: string | null; latest_date: string | null }
export interface FinanceInput { month: FinanceMonth; vehicles: FinanceVehicle[]; recurring_costs: RecurringCost[]; insurance: Insurance[]; expenses: FinanceExpense[]; ehailing: EhailingPayment[]; smart_import: FinanceImport | null; smart_rows: SmartDriveRow[]; imports: FinanceImport[]; bootstrap_completed: boolean; calculation_version?: number; bank_imports?: import('./finance-bank').BankImport[]; bank_rows?: (import('./finance-bank').BankReviewRow & { import_id: string; expense_id?: string | null; match_valid?: boolean })[] }
export interface QualityIssue { code: string; severity: 'error' | 'warning'; detail: string; plate_key?: string | null; source_id?: string | null }
export interface FinanceTotals { cash: number; revenue: number; service_claim: number; commission: number; recurring: number; workshop: number; insurance: number; direct_costs: number; contribution: number; margin: number | null }
export interface VehicleContribution extends FinanceTotals { plate_key: string; display_plate: string; business_unit: BusinessUnit | 'UNMATCHED' }
export interface FinanceReport { vehicles: VehicleContribution[]; businesses: Record<BusinessUnit | 'UNMATCHED', FinanceTotals>; totals: FinanceTotals; corporate_opex: number; management_profit: number; issues: QualityIssue[] }
export interface ImportPreview<T> { rows: T[]; issues: QualityIssue[]; filename: string; report_month: string; total_rows: number; matched_rows: number; unmatched_rows: number; matched_vehicles: number; unmatched_vehicles: number; gross_revenue: number; commission: number }
export interface BootstrapData { vehicles: FinanceVehicle[]; recurring_costs: RecurringCost[]; insurance: Insurance[] }
