create table finance_private.section_uploads (
 id uuid primary key default gen_random_uuid(), finance_month date not null references finance_private.months(finance_month),
 kind text not null check(kind in ('VEHICLE_EXPENSE','CORPORATE_EXPENSE','VEHICLE','RECURRING_COST','INSURANCE')),
 filename text not null check(btrim(filename)<>''), source_hash text not null check(source_hash ~ '^[a-f0-9]{64}$'), imported_at timestamptz not null default now(), imported_by uuid not null,
 row_count integer not null check(row_count>0), total_amount numeric(16,2) not null default 0, source_audit jsonb not null default '[]'::jsonb, unique(kind,source_hash)
);
create index finance_section_uploads_month on finance_private.section_uploads(finance_month,kind,imported_at desc);
alter table finance_private.section_uploads enable row level security;
revoke all on finance_private.section_uploads from public,anon,authenticated;
create table finance_private.section_reviews (
 finance_month date not null references finance_private.months(finance_month), section text not null check(section in ('workshop','vehicle_expense','corporate_expense')),
 decision text not null check(decision in ('NONE','REVIEWED')), reviewed_at timestamptz not null default now(), reviewed_by uuid not null, fingerprint text not null, primary key(finance_month,section)
);
alter table finance_private.section_reviews enable row level security;
revoke all on finance_private.section_reviews from public,anon,authenticated;
create table finance_private.shared_cost_copies (
 source_expense_id uuid not null, target_month date not null references finance_private.months(finance_month), target_expense_id uuid not null references finance_private.expenses(id), copied_at timestamptz not null default now(), copied_by uuid not null,
 primary key(source_expense_id,target_month), unique(target_expense_id)
);
alter table finance_private.shared_cost_copies enable row level security;
revoke all on finance_private.shared_cost_copies from public,anon,authenticated;

create function finance_private.section_fingerprint(p_month date,p_section text) returns text language sql stable security definer set search_path='' as $$
 select coalesce(jsonb_agg(jsonb_build_array(e.id,e.billing_date,e.plate_key,e.category,e.payment_source,e.supplier,e.amount,e.reference,e.description) order by e.id)::text,'[]')
 from finance_private.expenses e where e.finance_month=p_month and ((p_section='workshop' and e.payment_source='Workshop Billing') or (p_section='vehicle_expense' and e.payment_source='Vehicle Direct Cost') or (p_section='corporate_expense' and e.payment_source='Corporate Opex'))
$$;
create function finance_private.workspace_meta(p_month date) returns jsonb language plpgsql security definer set search_path='' as $$
begin
 perform finance_private.require_admin();
 if p_month is null or extract(day from p_month)<>1 then raise exception 'Finance month must be the first day of a month'; end if;
 return jsonb_build_object('reviews',(select coalesce(jsonb_agg(jsonb_build_object('section',s.section,'decision',coalesce(r.decision,'NONE'),'reviewed_at',coalesce(r.reviewed_at,to_timestamp(0)),'valid',coalesce(r.fingerprint=finance_private.section_fingerprint(p_month,s.section),false)) order by s.section),'[]'::jsonb) from (values ('workshop'),('vehicle_expense'),('corporate_expense')) s(section) left join finance_private.section_reviews r on r.finance_month=p_month and r.section=s.section),'uploads',(select coalesce(jsonb_agg(jsonb_build_object('id',u.id,'kind',lower(u.kind),'filename',u.filename,'imported_at',u.imported_at,'row_count',u.row_count,'total_amount',u.total_amount,'source_audit',u.source_audit) order by u.imported_at desc,u.id),'[]'::jsonb) from finance_private.section_uploads u where u.finance_month=p_month));
end$$;
create function finance_private.review_section(p_month date,p_section text,p_decision text,p_revision integer) returns jsonb language plpgsql security definer set search_path='' as $$
declare has_rows boolean;begin
 perform finance_private.lock_finance(); perform finance_private.require_draft(p_month);
 if p_revision is distinct from (select revision from finance_private.months where finance_month=p_month) then raise exception 'Month changed. Reload and review before continuing.'; end if;
 if p_section not in ('workshop','vehicle_expense','corporate_expense') or p_decision not in ('NONE','REVIEWED') then raise exception 'Invalid section review'; end if;
 select exists(select 1 from finance_private.expenses e where e.finance_month=p_month and ((p_section='workshop' and e.payment_source='Workshop Billing') or (p_section='vehicle_expense' and e.payment_source='Vehicle Direct Cost') or (p_section='corporate_expense' and e.payment_source='Corporate Opex'))) into has_rows;
 if p_decision='NONE' and has_rows then raise exception 'A non-empty section cannot be marked none'; end if;
 insert into finance_private.section_reviews(finance_month,section,decision,reviewed_at,reviewed_by,fingerprint) values(p_month,p_section,p_decision,now(),auth.uid(),finance_private.section_fingerprint(p_month,p_section)) on conflict(finance_month,section) do update set decision=excluded.decision,reviewed_at=excluded.reviewed_at,reviewed_by=excluded.reviewed_by,fingerprint=excluded.fingerprint;
 insert into finance_private.audit(actor,finance_month,action,details) values(auth.uid(),p_month,'REVIEW_FINANCE_SECTION',jsonb_build_object('section',p_section,'decision',p_decision));
 return finance_private.workspace_meta(p_month);
end$$;
create function finance_private.post_section_workbook(p_kind text,p_month date,p_filename text,p_rows jsonb,p_revision integer,p_source_hash text) returns jsonb language plpgsql security definer set search_path='' as $$
declare r jsonb; upload_id uuid; plate text; natural_id uuid; target_id uuid; total numeric:=0; expected_source text; allowed_categories text[];begin
 perform finance_private.lock_finance();perform finance_private.require_draft(p_month);
 if p_revision is distinct from (select revision from finance_private.months where finance_month=p_month) then raise exception 'Month changed. Reload and review before posting.';end if;
 if p_kind not in ('VEHICLE_EXPENSE','CORPORATE_EXPENSE','VEHICLE','RECURRING_COST','INSURANCE') then raise exception 'Invalid Finance section kind';end if;
 if nullif(btrim(p_filename),'') is null or p_source_hash !~ '^[a-f0-9]{64}$' then raise exception 'Filename and SHA-256 source hash are required';end if;
 if jsonb_typeof(p_rows) is distinct from 'array' or jsonb_array_length(p_rows)=0 then raise exception 'Invalid section rows';end if;
 if exists(select 1 from finance_private.section_uploads where kind=p_kind and source_hash=p_source_hash) then raise exception 'This workbook content was already imported for this section';end if;
 insert into finance_private.section_uploads(finance_month,kind,filename,source_hash,imported_by,row_count,source_audit) values(p_month,p_kind,p_filename,p_source_hash,auth.uid(),jsonb_array_length(p_rows),'[]'::jsonb) returning id into upload_id;
 for r in select value from jsonb_array_elements(p_rows) loop
  if nullif(r->>'sheet_name','') is null or coalesce((r->>'source_row')::integer,0)<1 then raise exception 'Source sheet and row are required';end if;
  plate:=nullif(regexp_replace(upper(r->>'plate_key'),'\s','','g'),'');
  if p_kind in ('VEHICLE_EXPENSE','CORPORATE_EXPENSE') then
   expected_source:=case when p_kind='VEHICLE_EXPENSE' then 'Vehicle Direct Cost' else 'Corporate Opex' end;
   allowed_categories:=case when p_kind='VEHICLE_EXPENSE' then array['Road Tax','APAD / Permit','Puspakom','Tyres','Battery','Repair','Accident','Towing','Restoration','Other Vehicle Cost'] else array['Office Rental','Accounting Fee','Salary','KWSP','PERKESO','PCB','Utilities','Internet','Professional Fees','General Software','Other Corporate Cost'] end;
   if (r->>'finance_month')::date is distinct from p_month or r->>'payment_source' is distinct from expected_source or (r->>'billing_date')::date is null or (r->>'billing_date')::date<p_month or (r->>'billing_date')::date>=p_month+interval '1 month' or nullif(btrim(r->>'category'),'') is null or (case when r->>'category'='Software' then 'General Software' else r->>'category' end)<>all(allowed_categories) or (r->>'amount')::numeric is null or (r->>'amount')::numeric<0 or (r->>'amount')::numeric<>round((r->>'amount')::numeric,2) then raise exception 'Invalid expense row';end if;
   if p_kind='VEHICLE_EXPENSE' and (plate is null or not exists(select 1 from finance_private.vehicles where plate_key=plate)) then raise exception 'Vehicle expense has an unknown vehicle';end if;
   if p_kind='CORPORATE_EXPENSE' and plate is not null then raise exception 'Corporate expense cannot have a vehicle';end if;
   if exists(select 1 from finance_private.expenses e where e.finance_month=p_month and e.billing_date=(r->>'billing_date')::date and e.plate_key is not distinct from plate and e.category=(case when r->>'category'='Software' then 'General Software' else r->>'category' end) and e.payment_source=expected_source and e.supplier is not distinct from r->>'supplier' and e.amount=(r->>'amount')::numeric and e.reference is not distinct from r->>'reference' and e.description is not distinct from r->>'description') then raise exception 'This Finance expense row was already imported';end if;
   insert into finance_private.expenses(finance_month,billing_date,plate_key,category,payment_source,supplier,amount,reference,description,source_row,sheet_name) values(p_month,(r->>'billing_date')::date,plate,case when r->>'category'='Software' then 'General Software' else r->>'category' end,expected_source,r->>'supplier',(r->>'amount')::numeric,r->>'reference',r->>'description',(r->>'source_row')::integer,r->>'sheet_name') returning id into target_id;total:=total+(r->>'amount')::numeric;
  elsif p_kind='VEHICLE' then
   if plate is null or nullif(btrim(r->>'display_plate'),'') is null or r->>'business_unit' not in ('E-HAILING','DAILY RENTAL','SMART DRIVE','SAMBUNG BAYAR') or nullif(btrim(r->>'ownership_type'),'') is null or nullif(btrim(r->>'status'),'') is null then raise exception 'Invalid vehicle master row';end if;
   perform finance_private.save_record('vehicle',jsonb_build_object('plate_key',plate,'display_plate',r->>'display_plate','business_unit',r->>'business_unit','ownership_type',r->>'ownership_type','status',r->>'status')); target_id:=null;
  elsif p_kind='RECURRING_COST' then
   if plate is null or not exists(select 1 from finance_private.vehicles where plate_key=plate) or (r->>'start_month')::date is null or extract(day from (r->>'start_month')::date)<>1 or (nullif(r->>'end_month','') is not null and (extract(day from (r->>'end_month')::date)<>1 or (r->>'end_month')::date<(r->>'start_month')::date)) or nullif(btrim(r->>'cost_type'),'') is null or (r->>'monthly_amount')::numeric is null or (r->>'monthly_amount')::numeric<0 or (r->>'monthly_amount')::numeric<>round((r->>'monthly_amount')::numeric,2) then raise exception 'Invalid recurring cost row';end if;
   select id into natural_id from finance_private.recurring_costs where plate_key=plate and start_month=(r->>'start_month')::date and cost_type=r->>'cost_type'; if (select count(*) from finance_private.recurring_costs where plate_key=plate and start_month=(r->>'start_month')::date and cost_type=r->>'cost_type')>1 then raise exception 'Ambiguous recurring cost natural key';end if;perform finance_private.save_record('recurring_cost',jsonb_build_object('id',natural_id,'plate_key',plate,'start_month',r->>'start_month','end_month',nullif(r->>'end_month',''),'cost_type',r->>'cost_type','monthly_amount',r->>'monthly_amount','payee',r->>'payee','notes',r->>'notes'));select id into target_id from finance_private.recurring_costs where plate_key=plate and start_month=(r->>'start_month')::date and cost_type=r->>'cost_type';total:=total+(r->>'monthly_amount')::numeric;
  else
   if plate is null or not exists(select 1 from finance_private.vehicles where plate_key=plate) or (r->>'premium')::numeric is null or (r->>'premium')::numeric<0 or (r->>'premium')::numeric<>round((r->>'premium')::numeric,2) or (r->>'coverage_start')::date is null or (r->>'coverage_end')::date is null or (r->>'coverage_end')::date<(r->>'coverage_start')::date then raise exception 'Invalid insurance row';end if;
   select id into natural_id from finance_private.insurance where plate_key=plate and coverage_start=(r->>'coverage_start')::date; if (select count(*) from finance_private.insurance where plate_key=plate and coverage_start=(r->>'coverage_start')::date)>1 then raise exception 'Ambiguous insurance natural key';end if;perform finance_private.save_record('insurance',jsonb_build_object('id',natural_id,'plate_key',plate,'premium',r->>'premium','payment_date',nullif(r->>'payment_date',''),'coverage_start',r->>'coverage_start','coverage_end',r->>'coverage_end'));select id into target_id from finance_private.insurance where plate_key=plate and coverage_start=(r->>'coverage_start')::date;total:=total+(r->>'premium')::numeric;
  end if;
  update finance_private.section_uploads set source_audit=source_audit || jsonb_build_array(jsonb_strip_nulls(jsonb_build_object('sheet_name',r->>'sheet_name','source_row',(r->>'source_row')::integer,'record_kind',lower(p_kind),'record_id',target_id,'plate_key',case when p_kind='VEHICLE' then plate else null end))) where id=upload_id;
 end loop;
 update finance_private.section_uploads set total_amount=total where id=upload_id;
 if p_kind in ('VEHICLE_EXPENSE','CORPORATE_EXPENSE') then update finance_private.months set revision=revision+1 where finance_month=p_month;end if;
 insert into finance_private.audit(actor,finance_month,action,details) values(auth.uid(),p_month,'IMPORT_FINANCE_SECTION',jsonb_build_object('upload_id',upload_id,'kind',p_kind));return finance_private.input(p_month);
end;$$;
create function finance_private.preview_previous_shared_costs(p_month date) returns jsonb language plpgsql security definer set search_path='' as $$
declare prev date:=p_month-interval '1 month'; frozen jsonb;begin
 perform finance_private.require_admin();if p_month is null or extract(day from p_month)<>1 then raise exception 'Finance month must be the first day of a month';end if;select frozen_input into frozen from finance_private.months where finance_month=prev and status='CLOSED';
 if frozen is not null then return coalesce((select jsonb_agg((x-'id')||jsonb_build_object('source_id',x->>'id','id',x->>'id','finance_month',p_month,'billing_date',(p_month+least(extract(day from (x->>'billing_date')::date)::integer,extract(day from(p_month+interval '1 month - 1 day'))::integer)-1)::text) order by x->>'id') from jsonb_array_elements(frozen->'expenses') x where x->>'payment_source'='Corporate Opex'),'[]'::jsonb);end if;
 return coalesce((select jsonb_agg(jsonb_build_object('source_id',e.id,'id',e.id,'finance_month',p_month,'billing_date',(p_month+least(extract(day from e.billing_date)::integer,extract(day from(p_month+interval '1 month - 1 day'))::integer)-1)::text,'plate_key',null,'category',e.category,'payment_source','Corporate Opex','supplier',e.supplier,'amount',e.amount,'reference',e.reference,'description',e.description) order by e.id) from finance_private.expenses e where e.finance_month=prev and e.payment_source='Corporate Opex'),'[]'::jsonb);
end$$;
create function finance_private.copy_previous_shared_costs(p_month date,p_rows jsonb,p_revision integer) returns jsonb language plpgsql security definer set search_path='' as $$
declare r jsonb; expected jsonb; source uuid; target uuid;begin
 perform finance_private.lock_finance();perform finance_private.require_draft(p_month);if p_revision is distinct from(select revision from finance_private.months where finance_month=p_month) then raise exception 'Month changed. Reload and review before posting.';end if;if jsonb_typeof(p_rows) is distinct from 'array' or jsonb_array_length(p_rows)=0 then raise exception 'Select one or more reviewed shared costs';end if;
 for r in select value from jsonb_array_elements(p_rows) loop source:=nullif(r->>'source_id','')::uuid;if source is null then raise exception 'Copied shared cost is missing its source';end if;select x into expected from jsonb_array_elements(finance_private.preview_previous_shared_costs(p_month)) x where x->>'source_id'=source::text;if expected is null or r is distinct from expected then raise exception 'Previous shared costs changed. Reload the preview before copying.';end if;if exists(select 1 from finance_private.shared_cost_copies where source_expense_id=source and target_month=p_month) then raise exception 'This shared cost was already copied to the selected month';end if;insert into finance_private.expenses(finance_month,billing_date,plate_key,category,payment_source,supplier,amount,reference,description) values(p_month,(expected->>'billing_date')::date,null,expected->>'category','Corporate Opex',expected->>'supplier',(expected->>'amount')::numeric,expected->>'reference',expected->>'description') returning id into target;insert into finance_private.shared_cost_copies(source_expense_id,target_month,target_expense_id,copied_by) values(source,p_month,target,auth.uid());end loop;
 update finance_private.months set revision=revision+1 where finance_month=p_month;insert into finance_private.audit(actor,finance_month,action,details) values(auth.uid(),p_month,'COPY_PREVIOUS_SHARED_COSTS',jsonb_build_object('count',jsonb_array_length(p_rows)));return finance_private.input(p_month);
end$$;
create function public.finance_workspace_meta(p_month date) returns jsonb language sql security invoker set search_path='' as $$select finance_private.workspace_meta(p_month)$$;
create function public.finance_review_section(p_month date,p_section text,p_decision text,p_revision integer) returns jsonb language sql security invoker set search_path='' as $$select finance_private.review_section(p_month,p_section,p_decision,p_revision)$$;
create function public.finance_post_section_workbook(p_kind text,p_month date,p_filename text,p_rows jsonb,p_revision integer,p_source_hash text) returns jsonb language sql security invoker set search_path='' as $$select finance_private.post_section_workbook(p_kind,p_month,p_filename,p_rows,p_revision,p_source_hash)$$;
create function public.finance_preview_previous_shared_costs(p_month date) returns jsonb language sql security invoker set search_path='' as $$select finance_private.preview_previous_shared_costs(p_month)$$;
create function public.finance_copy_previous_shared_costs(p_month date,p_rows jsonb,p_revision integer) returns jsonb language sql security invoker set search_path='' as $$select finance_private.copy_previous_shared_costs(p_month,p_rows,p_revision)$$;
revoke all on function finance_private.section_fingerprint(date,text),finance_private.workspace_meta(date),finance_private.review_section(date,text,text,integer),finance_private.post_section_workbook(text,date,text,jsonb,integer,text),finance_private.preview_previous_shared_costs(date),finance_private.copy_previous_shared_costs(date,jsonb,integer) from public,anon,authenticated;
revoke all on function public.finance_workspace_meta(date),public.finance_review_section(date,text,text,integer),public.finance_post_section_workbook(text,date,text,jsonb,integer,text),public.finance_preview_previous_shared_costs(date),public.finance_copy_previous_shared_costs(date,jsonb,integer) from public,anon,authenticated;
grant execute on function finance_private.workspace_meta(date),finance_private.review_section(date,text,text,integer),finance_private.post_section_workbook(text,date,text,jsonb,integer,text),finance_private.preview_previous_shared_costs(date),finance_private.copy_previous_shared_costs(date,jsonb,integer) to authenticated;
grant execute on function public.finance_workspace_meta(date),public.finance_review_section(date,text,text,integer),public.finance_post_section_workbook(text,date,text,jsonb,integer,text),public.finance_preview_previous_shared_costs(date),public.finance_copy_previous_shared_costs(date,jsonb,integer) to authenticated;
